2025-04-17 18:41:33,344 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:41:33,414 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 129, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:41:33,415 - INFO - 127.0.0.1 - - [17/Apr/2025 18:41:33] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:45:10,767 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:45:10,836 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 130, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:45:10,837 - INFO - 127.0.0.1 - - [17/Apr/2025 18:45:10] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:45:20,770 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:45:20,826 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 130, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:45:20,827 - INFO - 127.0.0.1 - - [17/Apr/2025 18:45:20] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:47:34,122 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:47:34,187 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 130, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:47:34,187 - INFO - 127.0.0.1 - - [17/Apr/2025 18:47:34] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:47:44,126 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:47:44,180 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 130, in gatherMetrics
    case _:
        ^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:47:44,181 - INFO - 127.0.0.1 - - [17/Apr/2025 18:47:44] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:47:54,124 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:47:54,178 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 130, in gatherMetrics
    case _:
        ^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:47:54,179 - INFO - 127.0.0.1 - - [17/Apr/2025 18:47:54] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:48:04,118 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:48:04,178 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 130, in gatherMetrics
    case _:
        ^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:48:04,179 - INFO - 127.0.0.1 - - [17/Apr/2025 18:48:04] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:48:34,125 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:48:34,199 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 129, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:48:34,200 - INFO - 127.0.0.1 - - [17/Apr/2025 18:48:34] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:48:36,270 - INFO - 127.0.0.1 - - [17/Apr/2025 18:48:36] "POST /renderMetrics HTTP/1.1" 200 -
2025-04-17 18:48:36,314 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:48:36,350 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 129, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:48:36,350 - INFO - 127.0.0.1 - - [17/Apr/2025 18:48:36] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:48:41,876 - INFO - 127.0.0.1 - - [17/Apr/2025 18:48:41] "POST /renderMetrics HTTP/1.1" 200 -
2025-04-17 18:48:41,921 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:48:41,960 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 129, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:48:41,961 - INFO - 127.0.0.1 - - [17/Apr/2025 18:48:41] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:48:51,927 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:48:51,986 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 129, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:48:51,987 - INFO - 127.0.0.1 - - [17/Apr/2025 18:48:51] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:49:01,923 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:49:01,972 - ERROR - Exception on /get_metrics_data [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/marcio.ribeiro/github/mongosync_metrics/mongosync_metrics_python/mongosync_plotly_internal_DB.py", line 129, in gatherMetrics
    vColor == "green"
    ^^^^^^
UnboundLocalError: cannot access local variable 'vColor' where it is not associated with a value
2025-04-17 18:49:01,973 - INFO - 127.0.0.1 - - [17/Apr/2025 18:49:01] "[35m[1mPOST /get_metrics_data HTTP/1.1[0m" 500 -
2025-04-17 18:50:08,742 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:50:08,856 - INFO - 127.0.0.1 - - [17/Apr/2025 18:50:08] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:50:18,742 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:50:18,815 - INFO - 127.0.0.1 - - [17/Apr/2025 18:50:18] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:50:28,741 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:50:28,818 - INFO - 127.0.0.1 - - [17/Apr/2025 18:50:28] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:50:38,740 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:50:38,817 - INFO - 127.0.0.1 - - [17/Apr/2025 18:50:38] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:50:48,742 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:50:48,842 - INFO - 127.0.0.1 - - [17/Apr/2025 18:50:48] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:50:58,735 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:50:58,806 - INFO - 127.0.0.1 - - [17/Apr/2025 18:50:58] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:51:08,741 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:51:08,816 - INFO - 127.0.0.1 - - [17/Apr/2025 18:51:08] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:51:18,741 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:51:18,815 - INFO - 127.0.0.1 - - [17/Apr/2025 18:51:18] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:51:28,739 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:51:28,817 - INFO - 127.0.0.1 - - [17/Apr/2025 18:51:28] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:51:38,739 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:51:38,821 - INFO - 127.0.0.1 - - [17/Apr/2025 18:51:38] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:51:48,740 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:51:48,815 - INFO - 127.0.0.1 - - [17/Apr/2025 18:51:48] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:51:58,741 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:51:58,816 - INFO - 127.0.0.1 - - [17/Apr/2025 18:51:58] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:52:08,739 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:52:08,814 - INFO - 127.0.0.1 - - [17/Apr/2025 18:52:08] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:52:18,739 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:52:18,806 - INFO - 127.0.0.1 - - [17/Apr/2025 18:52:18] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:54:28,749 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:54:28,870 - INFO - 127.0.0.1 - - [17/Apr/2025 18:54:28] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:54:38,736 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:54:38,804 - INFO - 127.0.0.1 - - [17/Apr/2025 18:54:38] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:54:48,738 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:54:48,815 - INFO - 127.0.0.1 - - [17/Apr/2025 18:54:48] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:54:58,744 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:54:58,822 - INFO - 127.0.0.1 - - [17/Apr/2025 18:54:58] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:55:08,735 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:55:08,816 - INFO - 127.0.0.1 - - [17/Apr/2025 18:55:08] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:55:18,732 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:55:18,790 - INFO - 127.0.0.1 - - [17/Apr/2025 18:55:18] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:55:28,734 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:55:28,795 - INFO - 127.0.0.1 - - [17/Apr/2025 18:55:28] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:55:38,735 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:55:38,793 - INFO - 127.0.0.1 - - [17/Apr/2025 18:55:38] "POST /get_metrics_data HTTP/1.1" 200 -
2025-04-17 18:55:48,732 - INFO - Connected to target MongoDB cluster.
2025-04-17 18:55:48,792 - INFO - 127.0.0.1 - - [17/Apr/2025 18:55:48] "POST /get_metrics_data HTTP/1.1" 200 -
